version: "3.9"
services:
  web:
    image: "${APP_IMAGE}:${TAG}"
    container_name: web
    environment:
      DJANGO_SETTINGS_MODULE: django_main.settings
      DB_HOST: rds-dev.swapapp.net
    ports:
      - "9090:9090"
    volumes:
      - "/var/app/current:/etc/django-static"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z ${DB_HOST} ${DB_PORT}"]
      interval: 15s
      timeout: 90s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"