# Default values for django app and MySQL database.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# MySQL Database Configuration
mysql:
  image:
    repository: public.ecr.aws/a9k6f9j6/mysql
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  env:
  - name: MYSQL_ROOT_PASSWORD
    value: root
  - name: MYSQL_DATABASE
    value: my_application
  - name: MYSQL_USER
    value: root
  - name: MYSQL_PASSWORD
    value: password
  resources: {}


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3306  # Ensure this port is correct for your service's needs

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
