version: 0.0
os: linux
files:
   - source: /
     destination: /var/code/
permissions:
   - object: /var/code/
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
       - directory
hooks:
   BeforeInstall:
    - location: Deployment/before_install.sh
      runas: ec2-user
      timeout: 300
   AfterInstall:
    - location: Deployment/after_install.sh
      runas: ec2-user
      timeout: 300
    ApplicationStart:
    - location: Deployment/application_start.sh
      runas: ec2-user
      timeout: 300
    ValidateService:
      - location: Deployment/validate_service.sh
        runas: ec2-user
        timeout: 300