apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-serviceaccount
  namespace: argocd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-role-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-serviceaccount
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
