apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-django-to-mysql
  namespace: development
spec:
  podSelector:
    matchLabels:
      app: django
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: db-mysql
