apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ExternalName
  externalName: mysql-service.development.svc.cluster.local
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database