version: "3.9"
services:
  web:
    image: public.ecr.aws/a9k6f9j6/django_swap:154639-280224
    container_name: web
    environment:
      DJANGO_SETTINGS_MODULE: django_main.settings
      DB_HOST: swap-webapp-dev.ebs-lab-mysql
    ports:
      - "8080:8080"
    volumes:
      - "/var/app/current:/etc/django-static"
    healthcheck:
      test: ["CMD", "nc", "-z", "${DB_HOST}", "3306"]
      interval: 10s
      timeout: 60s
      retries: 3