version: "3.9"
services:
  web:
    image: public.ecr.aws/a9k6f9j6/django_swap:154639-280224
    container_name: web
    environment:
      DJANGO_SETTINGS_MODULE: django_main.settings
      DB_HOST: swap-webapp-dev.ebs-lab-mysql
    ports:
      - "8080:8080"
    volumes:
      - "/var/app/current:/etc/django-static"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z ${DB_HOST} 3306"]
      interval: 15s
      timeout: 90s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"
