apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django
  labels:
    {{- include "django.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          # command: ["/bin/sh", "-c"]
          # args:
          #   - >
          #     sleep 5 &&
          #     python manage.py makemigrations &&
          #     sleep 5 &&
          #     python manage.py migrate &&
          #     sleep 5 &&
          #     python manage.py runserver 0.0.0.0:8080
          ports:
            - name: django
              containerPort: {{ .Values.django.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: django
            initialDelaySeconds: 36000  
            periodSeconds: 86400 
            failureThreshold: 3    
          readinessProbe:
            tcpSocket:
              port: django
            initialDelaySeconds: 36000 
            periodSeconds: 86400
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: django
            initialDelaySeconds: 30
            periodSeconds: 86400
            failureThreshold: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}