apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django
  labels:
    app: django
    tier: frontend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: django
      tier: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: django
        tier: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              sleep 5 &&
              python manage.py makemigrations &&
              sleep 5 &&
              python manage.py migrate &&
              sleep 5 &&
              python manage.py runserver 0.0.0.0:8080
          ports:
            - name: django
              containerPort: {{ .Values.django.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: {{ .Values.mysql.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql.probes.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.mysql.probes.livenessProbe.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: {{ .Values.mysql.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql.probes.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.mysql.probes.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


