apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-django-to-mysql
spec:
  podSelector:
    matchLabels:
      app: django-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: mysql-app
    ports:
    - protocol: TCP
      port: 3306