apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-django-to-mysql
spec:
  podSelector:
    matchLabels:
      app: db-mysql
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: client