apiVersion: v1
data:
  db_host: bXlzcWwtc2VydmljZS5kZXZlbG9wbWVudC5zdmMuY2x1c3Rlci5sb2NhbA==
  db_name: bXlfYXBwbGljYXRpb24=
  password: cGFzc3dvcmQ=
  root_password: cGFzc3dvcmQ=
  username: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: "2024-02-20T15:37:30Z"
  name: mysql-secret
  namespace: development
  resourceVersion: "359118"
  uid: 6cd93654-6191-4a10-b7e5-0bf04445b6a6
type: Opaque
