apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: django
    tier: frontend
  type: NodePort
