apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: django
    tier: frontend
  type: NodePort
