# Default values for Django app and MySQL database.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# MySQL Database Configuration
mysql:
  image:
    repository: mysql
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  labels:
    app: mysql-db
    tier: database
  probes:
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    startupProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: mysql-data-pvc
    - name: config-volume
      configMap:
        name: mysql-config
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

imagePullSecrets: []
podAnnotations: {}
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3306

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Ensure these are defined, even if empty, to avoid template rendering errors
nodeSelector: {}
tolerations: []
affinity: {}
