name: Build and Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set AWS account ID
        run: echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::884878220922:role/ecr.development.oicd.github.role
          aws-region: us-east-1 

      - name: Login to ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set Docker image tag
        id: set-tag
        run: |
          echo "TAG=$(date +'%H%M%S-%d%m%y')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd SWAP/django_swap/
          docker build -t public.ecr.aws/a9k6f9j6/django_swap:${{ env.TAG }} .

      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/a9k6f9j6/django_swap:${{ env.TAG }}