name: Build and Push Docker Image
env:
  tag: 


on:
  workflow_run:
    workflows: ["Build and Push Django Application to ECR"]
    types:
      - completed

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::884878220922:role/ecr.development.django.github.policy
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Login to ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

  build:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - name: Set Docker image tag
        id: set-tag
        run: |
          echo "TAG=$(date +'%d%m%y-%H%M%S')-v$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd SWAP/django_swap/
          docker build -t public.ecr.aws/a9k6f9j6/django_swap:${{ env.TAG }} .

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/a9k6f9j6/django_swap:${{ needs.build.outputs.TAG }}
